# SPDX-License-Identifier: AGPL-3.0-or-later
"""One host-path contract for Python, systemd, sshd and the packaged tooling.

``appliance.conf`` is the authority for where the EMS installation and the SFTP
export root live. Everything else is generated from it: the environment file
the export script reads, the drop-in the ``.path`` unit needs because a unit
cannot expand variables, and the sshd Match policy that confines the backup
account into the configured export root. Nothing here accepts a value from a
request, and every generated file is root-owned and removed on purge.

The generated set is written as one transaction. A half-applied configuration —
a new environment file next to an old chroot directory — would be a boundary
that neither the operator nor this code could describe.
"""

import os
from pathlib import Path

from appliance.paths import (
    ENV_BACKUP_USER,
    ENV_EXPORT_ROOT,
    ENV_EXPORT_STATUS_FILE,
    ENV_INSTALL_ROOT,
    atomic_write,
    validate_configured_root,
    validate_root_pair,
)

HOST_PATHS_NAME = "host-paths.env"
PATH_UNIT = "ems-appliance-export.path"
SSHD_POLICY_NAME = "ems-appliance-backup.conf"
DEFAULT_SYSTEMD_DIR = "/etc/systemd/system"
DEFAULT_SSHD_DIR = "/etc/ssh/sshd_config.d"

ARTIFACT_ENVIRONMENT = "environment_file"
ARTIFACT_PATH_UNIT = "path_unit_dropin"
ARTIFACT_SSHD_POLICY = "sshd_policy"

HEADER = (
    "# Generated by 'ems-appliance host-config --apply'. Do not edit.\n"
    "# The authority is /etc/ems-appliance-manager/appliance.conf.\n"
)

FORCED_COMMAND = (
    "internal-sftp -P symlink,hardlink,rename,posix-rename,remove,mkdir,rmdir,setstat,fsetstat"
)


class HostConfigError(Exception):
    def __init__(self, code, message):
        super().__init__(message)
        self.code = code
        self.message = message


def host_paths_file(paths):
    return paths.config_dir / HOST_PATHS_NAME


def path_unit_dropin(systemd_dir=DEFAULT_SYSTEMD_DIR):
    return Path(systemd_dir) / f"{PATH_UNIT}.d" / "host-paths.conf"


def sshd_policy_file(sshd_dir=DEFAULT_SSHD_DIR):
    return Path(sshd_dir) / SSHD_POLICY_NAME


def environment_values(paths, config):
    return {
        ENV_INSTALL_ROOT: str(paths.install_root),
        ENV_EXPORT_ROOT: str(paths.export_root),
        ENV_EXPORT_STATUS_FILE: str(paths.export_status_file),
        ENV_BACKUP_USER: config.backup_user,
    }


def render_environment(paths, config):
    values = environment_values(paths, config)
    return HEADER + "".join(f"{key}={value}\n" for key, value in sorted(values.items()))


def render_path_unit(paths):
    """A drop-in that replaces the packaged watch path instead of adding to it."""

    return HEADER + "[Path]\n" + "PathChanged=\n" + f"PathChanged={paths.install_root}\n"


def render_sshd_policy(paths, config):
    """The Match block that confines the backup account, for the configured root."""

    return (
        HEADER
        + f"Match User {config.backup_user}\n"
        + f"    ChrootDirectory {paths.export_root}\n"
        + "    PasswordAuthentication no\n"
        + "    KbdInteractiveAuthentication no\n"
        + "    PubkeyAuthentication yes\n"
        + "    PermitTTY no\n"
        + "    AllowTcpForwarding no\n"
        + "    AllowAgentForwarding no\n"
        + "    X11Forwarding no\n"
        + "    PermitTunnel no\n"
        + "    GatewayPorts no\n"
        + "    PermitOpen none\n"
        + f"    ForceCommand {FORCED_COMMAND}\n"
    )


def artifacts(paths, config, *, systemd_dir=DEFAULT_SYSTEMD_DIR, sshd_dir=DEFAULT_SSHD_DIR):
    """Every generated file, in the order it is written."""

    return (
        (ARTIFACT_ENVIRONMENT, host_paths_file(paths), render_environment(paths, config)),
        (ARTIFACT_PATH_UNIT, path_unit_dropin(systemd_dir), render_path_unit(paths)),
        (ARTIFACT_SSHD_POLICY, sshd_policy_file(sshd_dir), render_sshd_policy(paths, config)),
    )


def read_text(path):
    try:
        return Path(path).read_text(encoding="utf-8")
    except OSError:
        return ""


def read_environment(path):
    values = {}
    for line in read_text(path).splitlines():
        entry = line.strip()
        if not entry or entry.startswith("#") or "=" not in entry:
            continue
        key, _, value = entry.partition("=")
        values[key.strip()] = value.strip()
    return values


def validate_configuration(paths, config):
    validate_configured_root("the EMS installation root", str(paths.install_root))
    validate_configured_root("the export root", str(paths.export_root))
    validate_root_pair(paths.install_root, paths.export_root)
    return True


def _snapshot(targets):
    saved = {}
    for path in targets:
        try:
            saved[path] = path.read_text(encoding="utf-8")
        except OSError:
            saved[path] = None
    return saved


def _restore(saved, written):
    for path in written:
        previous = saved.get(path)
        try:
            if previous is None:
                path.unlink(missing_ok=True)
            else:
                atomic_write(path, previous, mode=0o644, owner_root=True)
        except OSError:
            continue


def apply_host_config(
    paths,
    config,
    *,
    systemd_dir=DEFAULT_SYSTEMD_DIR,
    sshd_dir=DEFAULT_SSHD_DIR,
    activation=None,
):
    """Generate every derived artefact, or leave the previous set in place."""

    validate_configuration(paths, config)
    planned = artifacts(paths, config, systemd_dir=systemd_dir, sshd_dir=sshd_dir)
    saved = _snapshot([path for _, path, _ in planned])
    written = []
    try:
        for _, path, text in planned:
            path.parent.mkdir(parents=True, exist_ok=True)
            atomic_write(path, text, mode=0o644, owner_root=True)
            written.append(path)
        if activation is not None:
            activation(paths, config)
    except (OSError, HostConfigError) as exc:
        _restore(saved, written)
        raise HostConfigError(
            "host_config_apply_failed",
            f"the generated host configuration was rolled back: {exc}",
        )

    return {
        "install_root": str(paths.install_root),
        "export_root": str(paths.export_root),
        "backup_user": config.backup_user,
        "environment_file": str(host_paths_file(paths)),
        "path_unit_dropin": str(path_unit_dropin(systemd_dir)),
        "sshd_policy": str(sshd_policy_file(sshd_dir)),
        "written": [str(path) for path in written],
        "error": "",
    }


def live_activation(*, runner=None, systemd=None):
    """Reload systemd and prove sshd still accepts its configuration.

    Returned as a callable so ``apply_host_config`` stays testable without a
    host, and so a failure here rolls the generated files back.
    """

    from appliance.commands import CommandRunner
    from appliance.systemd import UNIT_SSH, SystemdBackend

    runner = runner or CommandRunner()
    systemd = systemd or SystemdBackend(runner)

    def activate(paths, config):
        if runner.available("sshd") and not runner.run("sshd", ["-t"], timeout=30).ok:
            raise HostConfigError(
                "sshd_config_invalid", "the generated SSH policy is not accepted by sshd"
            )
        if not runner.available("systemctl"):
            return True
        if not runner.run("systemctl", ["daemon-reload"], timeout=60).ok:
            raise HostConfigError("daemon_reload_failed", "systemctl daemon-reload failed")
        if not runner.run("systemctl", ["restart", PATH_UNIT], timeout=60).ok:
            raise HostConfigError(
                "path_watcher_restart_failed", f"{PATH_UNIT} could not be re-armed"
            )
        try:
            if systemd.unit_state(UNIT_SSH)["running"] and not systemd.reload(UNIT_SSH).ok:
                raise HostConfigError("sshd_reload_failed", "the SSH daemon did not reload")
        except HostConfigError:
            raise
        except Exception:
            return True
        return True

    return activate


def effective_ssh_policy(config, *, runner=None):
    """What sshd would apply to the backup account, when it can be asked."""

    from appliance.ssh_service import parse_sshd_config

    if runner is None or not runner.available("sshd"):
        return {"available": False, "chroot": "", "user": config.backup_user}
    result = runner.run(
        "sshd",
        ["-T", "-C", f"user={config.backup_user},host=localhost,addr=127.0.0.1"],
        timeout=20,
    )
    if not result.ok:
        return {"available": False, "chroot": "", "user": config.backup_user}
    values = parse_sshd_config(result.stdout)
    return {
        "available": True,
        "chroot": str(values.get("chrootdirectory", "")),
        "user": config.backup_user,
    }


def active_watched_paths(runner=None):
    """The path the running watcher follows, when systemd can be asked."""

    if runner is None or not runner.available("systemctl"):
        return None
    result = runner.run("systemctl", ["show", PATH_UNIT, "-p", "Paths"], timeout=30)
    if not result.ok:
        return None
    values = []
    for token in (result.stdout or "").partition("=")[2].split():
        if token.startswith("/"):
            values.append(token)
    return values


def describe(
    paths,
    config,
    *,
    systemd_dir=DEFAULT_SYSTEMD_DIR,
    sshd_dir=DEFAULT_SSHD_DIR,
    runner=None,
):
    """What is configured, and whether every generated artefact still agrees."""

    drift = []
    environment = host_paths_file(paths)
    recorded = read_environment(environment)
    expected = environment_values(paths, config)
    drift.extend(sorted(key for key, value in expected.items() if recorded.get(key) != value))

    generated = {}
    for name, path, text in artifacts(
        paths, config, systemd_dir=systemd_dir, sshd_dir=sshd_dir
    ):
        present = path.is_file()
        matches = present and read_text(path) == text
        generated[name] = {"path": str(path), "present": present, "matches": matches}
        if name != ARTIFACT_ENVIRONMENT and not matches:
            drift.append(name)

    watched = ""
    for line in read_text(path_unit_dropin(systemd_dir)).splitlines():
        if line.startswith("PathChanged=") and line.partition("=")[2]:
            watched = line.partition("=")[2].strip()

    effective = effective_ssh_policy(config, runner=runner)
    if effective["available"] and effective["chroot"] != str(paths.export_root):
        drift.append("effective_ssh_chroot")

    active_paths = active_watched_paths(runner)
    if active_paths is not None and active_paths and str(paths.install_root) not in active_paths:
        drift.append("active_watched_path")

    return {
        "install_root": str(paths.install_root),
        "export_root": str(paths.export_root),
        "backup_user": config.backup_user,
        "environment_file": str(environment),
        "environment_present": environment.is_file(),
        "path_unit_dropin": str(path_unit_dropin(systemd_dir)),
        "sshd_policy_file": str(sshd_policy_file(sshd_dir)),
        "generated": generated,
        "watched_path": watched,
        "active_watched_paths": active_paths,
        "effective_ssh": effective,
        "consistent": not drift,
        "drift": sorted(set(drift)),
    }


def remove_generated(paths, *, systemd_dir=DEFAULT_SYSTEMD_DIR, sshd_dir=DEFAULT_SSHD_DIR):
    """Withdraw the generated policy; used by the package on purge."""

    removed = []
    for path in (
        host_paths_file(paths),
        path_unit_dropin(systemd_dir),
        sshd_policy_file(sshd_dir),
    ):
        try:
            path.unlink()
            removed.append(str(path))
        except OSError:
            continue
    for directory in (path_unit_dropin(systemd_dir).parent,):
        try:
            os.rmdir(directory)
        except OSError:
            continue
    return removed
