# SPDX-License-Identifier: AGPL-3.0-or-later
"""Bounded, redacted support archive.

Every member is generated by the appliance itself and passed through secret
redaction; no host file is copied verbatim. The manifest lists exactly what the
archive contains so a user can see it before sharing it.
"""

import base64
import io
import json
import tarfile
import time

from appliance.operations import STATE_SUCCEEDED
from appliance.redaction import bounded_redacted_log, redact_mapping
from appliance.version import APPLIANCE_VERSION

TYPE_SUPPORT_ARCHIVE = "support.archive"

EXCLUDED_BY_DEFAULT = (
    "passwords",
    "SSH private keys",
    "complete authorized_keys contents",
    "MQTT credentials",
    "EMS secrets",
    "tokens",
)

# The agent response cap is 8 MiB; base64 adds a third, so this leaves
# room for the envelope around the bytes.
MAX_ARCHIVE_BYTES = 5 * 1024 * 1024

MAX_LOG_LINES = 400



class SupportArchiveError(Exception):
    def __init__(self, code, message):
        super().__init__(message)
        self.code = code
        self.message = message
class SupportArchiveService:
    def __init__(self, *, paths, config, status_service, operations, time_fn=None):
        self.paths = paths
        self.config = config
        self.status_service = status_service
        self.operations = operations
        self._time = time_fn or time.time

    def plan(self, operation):
        members = [name for name, _ in self._members()]
        self.operations.update_target(operation.operation_id, {"members": members})
        return {
            "type": TYPE_SUPPORT_ARCHIVE,
            "members": members,
            "excluded": list(EXCLUDED_BY_DEFAULT),
            "destination": str(self._destination(operation.operation_id)),
        }

    def execute(self, operation):
        destination = self._destination(operation.operation_id)
        destination.parent.mkdir(parents=True, exist_ok=True)
        members = self._members()
        manifest = {
            "appliance_version": APPLIANCE_VERSION,
            "created_at": self._time(),
            "operation_id": operation.operation_id,
            "files": [name for name, _ in members],
            "excluded": list(EXCLUDED_BY_DEFAULT),
        }

        with tarfile.open(destination, "w:gz") as archive:
            for name, payload in members:
                self._add(archive, name, payload)
            self._add(archive, "manifest.json", json.dumps(manifest, indent=2, sort_keys=True))

        payload = {
            "path": str(destination),
            "size_bytes": destination.stat().st_size,
            "manifest": manifest,
        }
        self.operations.finish(operation.operation_id, STATE_SUCCEEDED, result=payload)
        return payload

    def read(self, operation_id):
        """Hand a finished archive to the caller.

        The web account never reads agent state directly -- everything
        privileged reaches it through this API and no other way -- so the bytes
        travel with the response rather than by relaxing the directory.
        """

        destination = self._destination(operation_id)
        try:
            data = destination.read_bytes()
        except OSError:
            raise SupportArchiveError(
                "support_archive_not_found",
                "no support archive exists for this operation",
            )
        if len(data) > MAX_ARCHIVE_BYTES:
            raise SupportArchiveError(
                "support_archive_too_large",
                "the support archive is too large to be served; copy it off over SFTP",
            )
        return {
            "name": destination.name,
            "size_bytes": len(data),
            "content_base64": base64.b64encode(data).decode("ascii"),
        }

    def _destination(self, operation_id):
        return self.paths.support_dir / f"support-{operation_id}.tar.gz"

    def _add(self, archive, name, text):
        data = text.encode("utf-8", errors="replace")
        info = tarfile.TarInfo(name=name)
        info.size = len(data)
        info.mtime = int(self._time())
        info.mode = 0o600
        archive.addfile(info, io.BytesIO(data))

    def _members(self):
        status = redact_mapping(self.status_service.overview())
        members = [("status.json", json.dumps(status, indent=2, sort_keys=True))]
        for source in ("appliance_web", "appliance_agent", "operations", "audit", "admin_container"):
            try:
                log = self.status_service.read_log(source, MAX_LOG_LINES)
                members.append((f"logs/{source}.log", log["text"]))
            except Exception as exc:
                members.append((f"logs/{source}.log", f"unavailable: {exc.__class__.__name__}"))
        try:
            packages = self.status_service.updates()
            members.append(("packages.json", json.dumps(packages, indent=2, sort_keys=True)))
        except Exception:
            members.append(("packages.json", "{}"))
        members.append(("ab-status.json", json.dumps(self._ab_state(), indent=2, sort_keys=True)))
        return members

    def _ab_state(self):
        """Bounded A/B evidence: slots, selector, pending trial, digests.

        Digests and build ids are what makes a fallback diagnosable after the
        fact. No signing material, no key path and no artifact content is ever
        included, and the whole payload goes through the same redaction as the
        rest of the archive.
        """

        try:
            payload = self.status_service.ab_state()
        except Exception as exc:
            return {"error": exc.__class__.__name__}
        state = payload.get("ab_state") or {}
        return redact_mapping(
            {
                "mode": payload.get("mode"),
                "ab_supported": payload.get("ab_supported"),
                "reason": payload.get("reason"),
                "active_slot": payload.get("active_slot"),
                "inactive_slot": payload.get("inactive_slot"),
                "tryboot": payload.get("tryboot"),
                "selector": payload.get("selector"),
                "drift": payload.get("drift"),
                "layout_id": payload.get("layout_id"),
                "os_build": payload.get("os_build"),
                "persistence": (payload.get("persistence") or {}).get("state"),
                "known_good_slot": state.get("known_good_slot"),
                "previous_slot": state.get("previous_slot"),
                "slots": state.get("slots"),
                "pending_trial": state.get("pending_trial"),
                "last_fallback": state.get("last_fallback"),
                "releases": [
                    {
                        "release_id": item.get("release_id"),
                        "release_version": item.get("release_version"),
                        "build_id": item.get("build_id"),
                        "archive_digest": item.get("archive_digest"),
                        "signed": item.get("signed"),
                    }
                    for item in (payload.get("releases") or [])
                ],
            }
        )


def redact_bundle_text(text):
    return bounded_redacted_log(text, max_lines=MAX_LOG_LINES)["text"]
