# SPDX-License-Identifier: AGPL-3.0-or-later
"""Bounded, redacted support archive.

Every member is generated by the appliance itself and passed through secret
redaction; no host file is copied verbatim. The manifest lists exactly what the
archive contains so a user can see it before sharing it.
"""

import io
import json
import tarfile
import time

from appliance.operations import STATE_SUCCEEDED
from appliance.redaction import bounded_redacted_log, redact_mapping
from appliance.version import APPLIANCE_VERSION

TYPE_SUPPORT_ARCHIVE = "support.archive"

EXCLUDED_BY_DEFAULT = (
    "passwords",
    "SSH private keys",
    "complete authorized_keys contents",
    "MQTT credentials",
    "EMS secrets",
    "tokens",
)

MAX_LOG_LINES = 400


class SupportArchiveService:
    def __init__(self, *, paths, config, status_service, operations, time_fn=None):
        self.paths = paths
        self.config = config
        self.status_service = status_service
        self.operations = operations
        self._time = time_fn or time.time

    def plan(self, operation):
        members = [name for name, _ in self._members()]
        self.operations.update_target(operation.operation_id, {"members": members})
        return {
            "type": TYPE_SUPPORT_ARCHIVE,
            "members": members,
            "excluded": list(EXCLUDED_BY_DEFAULT),
            "destination": str(self._destination(operation.operation_id)),
        }

    def execute(self, operation):
        destination = self._destination(operation.operation_id)
        destination.parent.mkdir(parents=True, exist_ok=True)
        members = self._members()
        manifest = {
            "appliance_version": APPLIANCE_VERSION,
            "created_at": self._time(),
            "operation_id": operation.operation_id,
            "files": [name for name, _ in members],
            "excluded": list(EXCLUDED_BY_DEFAULT),
        }

        with tarfile.open(destination, "w:gz") as archive:
            for name, payload in members:
                self._add(archive, name, payload)
            self._add(archive, "manifest.json", json.dumps(manifest, indent=2, sort_keys=True))

        payload = {
            "path": str(destination),
            "size_bytes": destination.stat().st_size,
            "manifest": manifest,
        }
        self.operations.finish(operation.operation_id, STATE_SUCCEEDED, result=payload)
        return payload

    def _destination(self, operation_id):
        return self.paths.state_dir / "support" / f"support-{operation_id}.tar.gz"

    def _add(self, archive, name, text):
        data = text.encode("utf-8", errors="replace")
        info = tarfile.TarInfo(name=name)
        info.size = len(data)
        info.mtime = int(self._time())
        info.mode = 0o600
        archive.addfile(info, io.BytesIO(data))

    def _members(self):
        status = redact_mapping(self.status_service.overview())
        members = [("status.json", json.dumps(status, indent=2, sort_keys=True))]
        for source in ("appliance_web", "appliance_agent", "operations", "audit", "admin_container"):
            try:
                log = self.status_service.read_log(source, MAX_LOG_LINES)
                members.append((f"logs/{source}.log", log["text"]))
            except Exception as exc:
                members.append((f"logs/{source}.log", f"unavailable: {exc.__class__.__name__}"))
        try:
            packages = self.status_service.updates()
            members.append(("packages.json", json.dumps(packages, indent=2, sort_keys=True)))
        except Exception:
            members.append(("packages.json", "{}"))
        return members


def redact_bundle_text(text):
    return bounded_redacted_log(text, max_lines=MAX_LOG_LINES)["text"]
