# SPDX-License-Identifier: AGPL-3.0-or-later
# The appliance's host identity lives on the persistent partition, so it
# survives an A/B slot switch. Only the key files are shared; sshd_config,
# moduli and the distro's own drop-ins stay slot-local, so one slot's OS
# configuration never follows the other's.
HostKey /var/lib/ems-appliance-manager/ssh/ssh_host_ed25519_key
HostKey /var/lib/ems-appliance-manager/ssh/ssh_host_rsa_key
HostKey /var/lib/ems-appliance-manager/ssh/ssh_host_ecdsa_key
