# SPDX-License-Identifier: AGPL-3.0-or-later
# The agent socket directory: root-owned, readable only by the appliance group.
d /run/ems-appliance-manager 0750 root ems-appliance -
d /var/lib/ems-appliance-manager 0750 ems-appliance-web ems-appliance -
d /var/lib/ems-appliance-manager/operations 0750 ems-appliance-web ems-appliance -
d /var/lib/ems-appliance-manager/known-good 0750 ems-appliance-web ems-appliance -
d /var/lib/ems-appliance-manager/ssh-keys 0750 ems-appliance-web ems-appliance -
d /var/lib/ems-appliance-manager/compose-backup 0750 ems-appliance-web ems-appliance -
d /var/lib/ems-appliance-manager/packages 0750 root root -
d /var/log/ems-appliance-manager 0750 ems-appliance-web ems-appliance -
