# SPDX-License-Identifier: AGPL-3.0-or-later
"""Zero-config setup helpers for the bundled docker-compose InfluxDB backend.

This module owns the *host-side* setup flow that makes the bundled InfluxDB
analytics backend work without the operator having to understand InfluxDB
tokens:

- generate a gitignored local secret file (``deploy/docker/influxdb.env``) with
  secure random tokens/passwords, merging into any existing file without ever
  overwriting secrets that are already there;
- select the right docker-compose files for the EMS + bundled-InfluxDB stack;
- build the ``docker compose ...`` command line.

It is import-side-effect-free and never runs Docker itself: the actual
subprocess call lives in ``emsctl.py`` so it stays mockable and so the running
controller never manages Docker. ``config.json`` remains the source of truth and
holds no secrets.
"""

import os
import secrets
from collections import OrderedDict

from ems.paths import BASE_DIR

# Host-side fallback URL for bundled mode when host_url is missing from a legacy
# config. The bundled InfluxDB publishes 8086 to the host loopback.
DEFAULT_HOST_URL = "http://127.0.0.1:8086"

# The only secret file path the bundled Compose overlays read (their env_file is
# fixed to this). A bundled install must keep secret_file at this default so the
# generated secrets and Compose's env_file stay in sync.
DEFAULT_SECRET_FILE = "deploy/docker/influxdb.env"

# Base compose file shipped for everyone (EMS only, no InfluxDB).
BASE_COMPOSE_FILE = "docker-compose.example.yml"
# Bundled InfluxDB service.
INFLUX_COMPOSE_FILE = "deploy/docker/compose.influxdb.yml"
# Overlay that feeds the same secret env file (INFLUXDB_TOKEN/ORG) to the EMS
# container. Only included when bundled InfluxDB is enabled, so the default
# non-InfluxDB ``docker compose up -d`` path is never affected.
EMS_INFLUX_ENV_COMPOSE_FILE = "deploy/docker/compose.ems-influx-env.yml"

# Secret keys that must never be printed and must never be regenerated when a
# value already exists in the secret file.
SECRET_KEYS = (
    "INFLUXDB_TOKEN",
    "DOCKER_INFLUXDB_INIT_PASSWORD",
    "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN",
)

ENV_HEADER = (
    "# Generated by: python3 emsctl.py influx init\n"
    "# Local secrets for the bundled EMS InfluxDB analytics backend.\n"
    "# This file is gitignored. Do not commit it.\n"
    "#\n"
    "# INFLUXDB_TOKEN is read by EMS/emsctl via influxdb.token_env in\n"
    "# config.json. The DOCKER_INFLUXDB_INIT_* values bootstrap InfluxDB on its\n"
    "# first start only (an empty data volume); changing them later does not\n"
    "# re-initialize an existing database.\n"
)


def generate_secret():
    """Return a secure URL-safe random token suitable for InfluxDB."""
    return secrets.token_urlsafe(32)


def resolve_secret_file_path(influx_config, base_dir=None):
    """Absolute path to the configured secret env file."""
    base_dir = base_dir or BASE_DIR
    secret_file = influx_config.get("secret_file") or DEFAULT_SECRET_FILE
    if os.path.isabs(secret_file):
        return secret_file
    return os.path.join(base_dir, secret_file)


def host_cli_url(influx_config):
    """URL host-side CLI operations (init/sync/status) should connect to.

    Bundled InfluxDB runs in Docker, where the compose service name ``influxdb``
    used by ``influxdb.url`` is not resolvable from the host, so bundled mode
    uses ``host_url`` (default ``http://127.0.0.1:8086``). External mode keeps
    using ``url`` because the operator points it at a host-reachable address.
    """
    if influx_config.get("mode") == "bundled":
        return (influx_config.get("host_url") or DEFAULT_HOST_URL).strip()
    return (influx_config.get("url") or "").strip()


def uses_default_secret_file(influx_config):
    """True when ``secret_file`` matches the path the Compose overlays read.

    The bundled Compose overlays hard-code ``env_file: deploy/docker/influxdb.env``,
    so a non-default ``secret_file`` would let ``influx init`` write secrets the
    container never reads. Callers use this to refuse starting in that case.
    """
    configured = influx_config.get("secret_file") or DEFAULT_SECRET_FILE
    return os.path.normpath(configured) == os.path.normpath(DEFAULT_SECRET_FILE)


def parse_env_file(text):
    """Parse ``KEY=VALUE`` lines into an OrderedDict (comments/blanks skipped)."""
    values = OrderedDict()
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key:
            values[key] = value.strip()
    return values


def _redact(value):
    """Redacted representation of a secret value for human/JSON output."""
    if not value:
        return "(empty)"
    return f"set ({len(value)} chars, redacted)"


def build_env_values(influx_config, existing=None):
    """Merge expected env values over an existing env mapping.

    Secrets are generated only when missing; existing values (secret or not)
    are always preserved. Non-secret values are derived from ``config.json``
    when missing. Any unknown keys already in the file are kept as-is.

    Returns ``(values, generated_keys)`` where ``values`` is an OrderedDict in
    a stable order and ``generated_keys`` lists the secret keys created in this
    call.
    """
    existing = OrderedDict(existing or {})
    org = (influx_config.get("org") or "ems").strip() or "ems"
    bucket_prefix = (influx_config.get("bucket_prefix") or "ems").strip() or "ems"
    init_bucket = f"{bucket_prefix}_raw"

    generated_keys = []

    def take_secret(key, fallback=None):
        current = existing.get(key)
        if current:
            return current
        value = fallback if fallback is not None else generate_secret()
        generated_keys.append(key)
        return value

    # The main API token EMS uses. For a simple local install the admin token
    # mirrors it; if the user already has a distinct admin token we keep it.
    token = take_secret("INFLUXDB_TOKEN")
    admin_token = take_secret("DOCKER_INFLUXDB_INIT_ADMIN_TOKEN", fallback=token)
    password = take_secret("DOCKER_INFLUXDB_INIT_PASSWORD")

    values = OrderedDict()
    values["INFLUXDB_ORG"] = existing.get("INFLUXDB_ORG") or org
    values["INFLUXDB_TOKEN"] = token
    values["DOCKER_INFLUXDB_INIT_MODE"] = (
        existing.get("DOCKER_INFLUXDB_INIT_MODE") or "setup"
    )
    values["DOCKER_INFLUXDB_INIT_USERNAME"] = (
        existing.get("DOCKER_INFLUXDB_INIT_USERNAME") or "admin"
    )
    values["DOCKER_INFLUXDB_INIT_PASSWORD"] = password
    values["DOCKER_INFLUXDB_INIT_ORG"] = (
        existing.get("DOCKER_INFLUXDB_INIT_ORG") or org
    )
    values["DOCKER_INFLUXDB_INIT_BUCKET"] = (
        existing.get("DOCKER_INFLUXDB_INIT_BUCKET") or init_bucket
    )
    values["DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"] = admin_token

    # Preserve any extra keys the operator added that we don't manage.
    for key, value in existing.items():
        if key not in values:
            values[key] = value

    return values, generated_keys


def render_env_file(values):
    """Render the env file content (header + KEY=VALUE lines)."""
    lines = [ENV_HEADER, ""]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def write_env_file(path, content):
    """Write ``content`` to ``path`` with restrictive 0600 permissions."""
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    # Open with O_CREAT|O_WRONLY|O_TRUNC and 0600 so the secret file is not
    # group/world readable on platforms that honor the mode.
    flags = os.O_CREAT | os.O_WRONLY | os.O_TRUNC
    fd = os.open(path, flags, 0o600)
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
    finally:
        # On platforms where O_CREAT mode was ignored (e.g. pre-existing file),
        # tighten permissions explicitly. Best-effort; ignore unsupported FS.
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass


def ensure_secret_file(influx_config, base_dir=None):
    """Create or merge the bundled InfluxDB secret env file.

    Idempotent: an existing file keeps its secrets; only missing keys are
    added. Returns a redacted, machine-friendly report (no raw secrets).
    """
    base_dir = base_dir or BASE_DIR
    path = resolve_secret_file_path(influx_config, base_dir=base_dir)
    existed = os.path.exists(path)

    existing = OrderedDict()
    if existed:
        with open(path, "r", encoding="utf-8") as handle:
            existing = parse_env_file(handle.read())

    values, generated_keys = build_env_values(influx_config, existing)
    content = render_env_file(values)
    write_env_file(path, content)

    summary = OrderedDict()
    for key, value in values.items():
        if key in SECRET_KEYS:
            summary[key] = _redact(value)
        else:
            summary[key] = value

    return {
        "path": path,
        "relative_path": os.path.relpath(path, base_dir),
        "created": not existed,
        "generated_keys": generated_keys,
        "summary": summary,
    }


def read_secret_file_token(influx_config, base_dir=None):
    """Read the token named by ``token_env`` from the secret file, if present.

    Returns an empty string when the file or key is missing. Used so bundled
    mode resolves a token on the host without the operator exporting env vars.
    """
    base_dir = base_dir or BASE_DIR
    path = resolve_secret_file_path(influx_config, base_dir=base_dir)
    if not os.path.exists(path):
        return ""
    token_env = (influx_config.get("token_env") or "INFLUXDB_TOKEN").strip()
    with open(path, "r", encoding="utf-8") as handle:
        values = parse_env_file(handle.read())
    return values.get(token_env, "").strip()


def compose_files(influx_config):
    """Return the ordered docker-compose files for the current config.

    Bundled InfluxDB adds the InfluxDB service and the EMS env overlay; any
    other configuration (disabled, or external mode) uses only the base EMS
    compose file so the default ``docker compose up -d`` path is unchanged.
    """
    files = [BASE_COMPOSE_FILE]
    if influx_config.get("enabled") and influx_config.get("mode") == "bundled":
        files.append(INFLUX_COMPOSE_FILE)
        files.append(EMS_INFLUX_ENV_COMPOSE_FILE)
    return files


def build_compose_command(files, action=("up", "-d"), binary=("docker", "compose")):
    """Build the ``docker compose -f ... <action>`` argument vector."""
    command = list(binary)
    for compose_file in files:
        command.extend(["-f", compose_file])
    command.extend(action)
    return command
