# SPDX-License-Identifier: AGPL-3.0-or-later
"""Setup and command helpers for the bundled InfluxDB backend."""

import os
import secrets
import shlex
from collections import OrderedDict

from ems.paths import BASE_DIR

INFLUX_SERVICE = "influxdb"
INFLUX_CONTAINER_NAME = "ems-influxdb"
INFLUX_BACKUP_METHOD = "influx backup"

DEFAULT_HOST_URL = "http://127.0.0.1:8086"

# Must match the env_file path used by the bundled compose overlays.
DEFAULT_SECRET_FILE = "deploy/docker/influxdb.env"

# Docker-first secret path: secrets live next to config.json under the mounted
# config/ folder, the only writable location in the EMS/Admin container images.
DOCKER_FIRST_SECRET_FILE = "config/influxdb.env"

# Must match the bundled InfluxDB bind mount.
DEFAULT_DATA_DIR = "data/influxdb"

DEFAULT_CLI_CONFIG_NAME = "ems"

BASE_COMPOSE_FILE = "docker-compose.example.yml"
INFLUX_COMPOSE_FILE = "deploy/docker/compose.influxdb.yml"
EMS_INFLUX_ENV_COMPOSE_FILE = "deploy/docker/compose.ems-influx-env.yml"

# Preserve existing secret values; never print or regenerate these.
SECRET_KEYS = (
    "INFLUXDB_TOKEN",
    "DOCKER_INFLUXDB_INIT_PASSWORD",
    "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN",
)

ENV_HEADER = (
    "# Generated by: python3 emsctl.py influx init\n"
    "# Local secrets for the bundled EMS InfluxDB analytics backend.\n"
    "# This file is gitignored. Do not commit it.\n"
    "#\n"
    "# INFLUXDB_TOKEN is read by EMS/emsctl via influxdb.token_env in\n"
    "# config.json. The DOCKER_INFLUXDB_INIT_* values bootstrap InfluxDB on its\n"
    "# first start only (an empty data volume); changing them later does not\n"
    "# re-initialize an existing database.\n"
)


def generate_secret():
    """Return a secure URL-safe random token suitable for InfluxDB.

    The token reaches ``influx setup`` inside the InfluxDB container as a
    command-line argument, where a leading hyphen reads as a flag instead of a
    value and shifts every following argument by one. Resampling rules that
    shape out while keeping the alphabet and length; the entropy cost is a few
    hundredths of a bit.
    """

    while True:
        token = secrets.token_urlsafe(32)
        if not token.startswith("-"):
            return token


def resolve_secret_file_path(influx_config, base_dir=None):
    """Absolute path to the configured secret env file."""
    base_dir = base_dir or BASE_DIR
    secret_file = influx_config.get("secret_file") or DEFAULT_SECRET_FILE
    if os.path.isabs(secret_file):
        return secret_file
    return os.path.join(base_dir, secret_file)


def resolve_data_dir_path(base_dir=None):
    """Absolute path to the bundled InfluxDB local data directory."""
    base_dir = base_dir or BASE_DIR
    return os.path.join(base_dir, DEFAULT_DATA_DIR)


def ensure_data_dir(base_dir=None):
    """Create the bundled InfluxDB local data directory (idempotent).

    Returns the repo-root-relative path (``data/influxdb``). Docker would create
    the bind-mount target itself, but pre-creating it keeps ownership with the
    invoking user and makes the on-disk layout obvious before the container
    starts.
    """
    os.makedirs(resolve_data_dir_path(base_dir=base_dir), exist_ok=True)
    return DEFAULT_DATA_DIR


def host_cli_url(influx_config):
    """URL host-side CLI operations (init/sync/status) should connect to.

    Bundled InfluxDB runs in Docker, where the compose service name ``influxdb``
    used by ``influxdb.url`` is not resolvable from the host, so bundled mode
    uses ``host_url`` (default ``http://127.0.0.1:8086``). External mode keeps
    using ``url`` because the operator points it at a host-reachable address.
    """
    if influx_config.get("mode") == "bundled":
        return (influx_config.get("host_url") or DEFAULT_HOST_URL).strip()
    return (influx_config.get("url") or "").strip()


def uses_default_secret_file(influx_config):
    """True when ``secret_file`` matches the path the Compose overlays read.

    The bundled Compose overlays hard-code ``env_file: deploy/docker/influxdb.env``,
    so a non-default ``secret_file`` would let ``influx init`` write secrets the
    container never reads. Callers use this to refuse starting in that case.
    """
    configured = influx_config.get("secret_file") or DEFAULT_SECRET_FILE
    return os.path.normpath(configured) == os.path.normpath(DEFAULT_SECRET_FILE)


def parse_env_file(text):
    """Parse ``KEY=VALUE`` lines into an OrderedDict (comments/blanks skipped)."""
    values = OrderedDict()
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key:
            values[key] = value.strip()
    return values


def _redact(value):
    """Redacted representation of a secret value for human/JSON output."""
    if not value:
        return "(empty)"
    return f"set ({len(value)} chars, redacted)"


def build_env_values(influx_config, existing=None):
    """Merge expected env values over an existing env mapping.

    Secrets are generated only when missing; existing values (secret or not)
    are always preserved. Non-secret values are derived from ``config.json``
    when missing. Any unknown keys already in the file are kept as-is.

    Returns ``(values, generated_keys)`` where ``values`` is an OrderedDict in
    a stable order and ``generated_keys`` lists the secret keys created in this
    call.
    """
    existing = OrderedDict(existing or {})
    org = (influx_config.get("org") or "ems").strip() or "ems"
    bucket_prefix = (influx_config.get("bucket_prefix") or "ems").strip() or "ems"
    init_bucket = f"{bucket_prefix}_raw"

    generated_keys = []

    def take_secret(key, fallback=None):
        current = existing.get(key)
        if current:
            return current
        value = fallback if fallback is not None else generate_secret()
        generated_keys.append(key)
        return value

    # The main API token EMS uses. For a simple local install the admin token
    # mirrors it; if the user already has a distinct admin token we keep it.
    token = take_secret("INFLUXDB_TOKEN")
    admin_token = take_secret("DOCKER_INFLUXDB_INIT_ADMIN_TOKEN", fallback=token)
    password = take_secret("DOCKER_INFLUXDB_INIT_PASSWORD")

    values = OrderedDict()
    values["INFLUXDB_ORG"] = existing.get("INFLUXDB_ORG") or org
    values["INFLUXDB_TOKEN"] = token
    values["DOCKER_INFLUXDB_INIT_MODE"] = (
        existing.get("DOCKER_INFLUXDB_INIT_MODE") or "setup"
    )
    values["DOCKER_INFLUXDB_INIT_USERNAME"] = (
        existing.get("DOCKER_INFLUXDB_INIT_USERNAME") or "admin"
    )
    values["DOCKER_INFLUXDB_INIT_PASSWORD"] = password
    values["DOCKER_INFLUXDB_INIT_ORG"] = (
        existing.get("DOCKER_INFLUXDB_INIT_ORG") or org
    )
    values["DOCKER_INFLUXDB_INIT_BUCKET"] = (
        existing.get("DOCKER_INFLUXDB_INIT_BUCKET") or init_bucket
    )
    values["DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"] = admin_token
    values["DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME"] = (
        existing.get("DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME") or DEFAULT_CLI_CONFIG_NAME
    )

    # Preserve any extra keys the operator added that we don't manage.
    for key, value in existing.items():
        if key not in values:
            values[key] = value

    return values, generated_keys


def render_env_file(values):
    """Render the env file content (header + KEY=VALUE lines)."""
    lines = [ENV_HEADER, ""]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def write_env_file(path, content):
    """Write ``content`` to ``path`` with restrictive 0600 permissions."""
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    # Open with O_CREAT|O_WRONLY|O_TRUNC and 0600 so the secret file is not
    # group/world readable on platforms that honor the mode.
    flags = os.O_CREAT | os.O_WRONLY | os.O_TRUNC
    fd = os.open(path, flags, 0o600)
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
    finally:
        # On platforms where O_CREAT mode was ignored (e.g. pre-existing file),
        # tighten permissions explicitly. Best-effort; ignore unsupported FS.
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass


def ensure_secret_file(influx_config, base_dir=None):
    """Create or merge the bundled InfluxDB secret env file.

    Idempotent: an existing file keeps its secrets; only missing keys are
    added. Returns a redacted, machine-friendly report (no raw secrets).
    """
    base_dir = base_dir or BASE_DIR
    path = resolve_secret_file_path(influx_config, base_dir=base_dir)
    existed = os.path.exists(path)

    existing = OrderedDict()
    if existed:
        with open(path, encoding="utf-8") as handle:
            existing = parse_env_file(handle.read())

    values, generated_keys = build_env_values(influx_config, existing)
    content = render_env_file(values)
    write_env_file(path, content)

    summary = OrderedDict()
    for key, value in values.items():
        if key in SECRET_KEYS:
            summary[key] = _redact(value)
        else:
            summary[key] = value

    return {
        "path": path,
        "relative_path": os.path.relpath(path, base_dir),
        "created": not existed,
        "generated_keys": generated_keys,
        "summary": summary,
    }


def read_secret_file_token(influx_config, base_dir=None):
    """Read the token named by ``token_env`` from the secret file, if present.

    Returns an empty string when the file or key is missing. Used so bundled
    mode resolves a token on the host without the operator exporting env vars.
    """
    base_dir = base_dir or BASE_DIR
    path = resolve_secret_file_path(influx_config, base_dir=base_dir)
    if not os.path.exists(path):
        return ""
    token_env = (influx_config.get("token_env") or "INFLUXDB_TOKEN").strip()
    with open(path, encoding="utf-8") as handle:
        values = parse_env_file(handle.read())
    return values.get(token_env, "").strip()


OFFICIAL_APP_DIR = "/app"


def _in_official_app_layout(
    base_dir=None, app_dir=OFFICIAL_APP_DIR, path_exists=os.path.exists
):
    # /.dockerenv also exists in CI/devcontainers, so it alone is too broad.
    # Only the official image layout (app at /app with mounted config/data)
    # counts as the EMS Docker runtime. Mirrors ems.backup._in_official_app_layout
    # (kept local to avoid an import cycle: backup imports influx_setup).
    base_dir = base_dir or BASE_DIR
    return (
        os.path.abspath(base_dir) == app_dir
        and path_exists(os.path.join(app_dir, "config"))
        and path_exists(os.path.join(app_dir, "data"))
    )


def is_container_runtime(
    *, environ=None, docker_env_path="/.dockerenv", base_dir=None,
    app_dir=OFFICIAL_APP_DIR,
):
    """Best-effort detection of whether EMS runs as the official Docker image.

    Used to decide which bundled InfluxDB URL the runtime should use: the Docker
    service name (``influxdb.url``) inside the container, or the host loopback
    (``influxdb.host_url``) on a native host. Detection order:

    1. Explicit ``EMS_IN_CONTAINER`` override (``1``/``true`` or ``0``/``false``)
       so the compose overlay and tests can pin the answer.
    2. The Docker marker ``/.dockerenv`` *and* the official ``/app`` layout
       (``/app/config`` + ``/app/data``). The marker alone is not enough, so a
       generic devcontainer/CI container is not mistaken for the EMS image.
    """
    environ = os.environ if environ is None else environ
    flag = str(environ.get("EMS_IN_CONTAINER", "")).strip().lower()
    if flag in ("1", "true", "yes", "on"):
        return True
    if flag in ("0", "false", "no", "off"):
        return False
    return os.path.exists(docker_env_path) and _in_official_app_layout(
        base_dir, app_dir
    )


def runtime_influx_url(influx_config, *, environ=None):
    """URL the EMS runtime / dashboard analytics should connect to.

    Bundled mode on a native host must reach the container's published port via
    the host loopback (``host_url``, default ``http://127.0.0.1:8086``) because
    the Docker service name in ``url`` is not resolvable outside the Docker
    network. Bundled mode *inside* a container keeps using ``url`` (the service
    name). External mode always uses the operator-configured ``url``.
    """
    if influx_config.get("mode") == "bundled" and not is_container_runtime(
        environ=environ
    ):
        return host_cli_url(influx_config)
    return (influx_config.get("url") or "").strip()


def runtime_influx_token(influx_config, *, environ=None, base_dir=None):
    """Token the EMS runtime / dashboard analytics should use.

    Resolution order:

    1. Explicit ``influxdb.token`` from config.
    2. ``influxdb.token_env`` from the process environment.
    3. Bundled mode only: ``INFLUXDB_TOKEN`` (``token_env``) read from the
       generated secret file, so a native-host bundled install works without the
       operator exporting the token manually.

    External mode never reads the bundled secret file. Returns an empty string
    when no usable token exists (callers treat that as "not configured").
    """
    # Resolve config/env first (explicit token, then token_env). Imported
    # locally so this lightweight setup module stays cheap to import.
    from ems.config import resolve_influx_token

    token = resolve_influx_token(influx_config, environ=environ)
    if token:
        return token
    if influx_config.get("mode") == "bundled":
        return read_secret_file_token(influx_config, base_dir=base_dir)
    return ""


def compose_files(influx_config):
    """Return the ordered docker-compose files for the current config.

    Bundled InfluxDB adds the InfluxDB service and the EMS env overlay; any
    other configuration (disabled, or external mode) uses only the base EMS
    compose file so the default ``docker compose up -d`` path is unchanged.
    """
    files = [BASE_COMPOSE_FILE]
    if influx_config.get("enabled") and influx_config.get("mode") == "bundled":
        files.append(INFLUX_COMPOSE_FILE)
        files.append(EMS_INFLUX_ENV_COMPOSE_FILE)
    return files


def build_compose_command(files, action=("up", "-d"), binary=("docker", "compose")):
    """Build the ``docker compose -f ... <action>`` argument vector."""
    command = list(binary)
    for compose_file in files:
        command.extend(["-f", compose_file])
    command.extend(action)
    return command


# ---------------------------------------------------------------------------
# Bundled InfluxDB backup/restore command builders
#
# Build docker compose commands without exposing the token on the host CLI: the
# container already has ``INFLUXDB_TOKEN`` in its environment, so commands
# reference ``"$INFLUXDB_TOKEN"`` inside a ``sh -c`` wrapper.
# ---------------------------------------------------------------------------

def build_influx_backup_command(
    files, container_dir, *, token_env="INFLUXDB_TOKEN", binary=("docker", "compose")
):
    """Build the official ``influx backup`` command run inside the container."""
    inner = (
        f'influx backup {shlex.quote(container_dir)} -t "${token_env}"'
    )
    action = ("exec", "-T", INFLUX_SERVICE, "sh", "-c", inner)
    return build_compose_command(files, action=action, binary=binary)


def build_influx_restore_command(
    files, container_dir, *, token_env="INFLUXDB_TOKEN", binary=("docker", "compose")
):
    """Build the official replace-style InfluxDB restore command."""
    inner = (
        f'influx restore --full {shlex.quote(container_dir)} -t "${token_env}"'
    )
    action = ("exec", "-T", INFLUX_SERVICE, "sh", "-c", inner)
    return build_compose_command(files, action=action, binary=binary)


def build_influx_exec_command(files, argv, binary=("docker", "compose")):
    """Build a plain ``docker compose exec -T influxdb <argv...>`` command."""
    action = ("exec", "-T", INFLUX_SERVICE) + tuple(argv)
    return build_compose_command(files, action=action, binary=binary)


def build_influx_copy_out_command(
    files, container_path, host_path, binary=("docker", "compose")
):
    """Build ``docker compose cp influxdb:<container_path> <host_path>``."""
    action = ("cp", f"{INFLUX_SERVICE}:{container_path}", host_path)
    return build_compose_command(files, action=action, binary=binary)


def build_influx_copy_in_command(
    files, host_path, container_path, binary=("docker", "compose")
):
    """Build ``docker compose cp <host_path> influxdb:<container_path>``."""
    action = ("cp", host_path, f"{INFLUX_SERVICE}:{container_path}")
    return build_compose_command(files, action=action, binary=binary)


# ---------------------------------------------------------------------------
# In-container InfluxDB backup/restore (Docker-first mode)
#
# When EMS runs inside the official container it talks to the bundled InfluxDB
# over the Docker network and runs the official ``influx`` CLI directly, with no
# Docker CLI or socket. The host/token are passed via the environment so they
# never appear in argv.
# ---------------------------------------------------------------------------

INFLUX_CLI_BINARY = "influx"


def build_influx_cli_backup_argv(staging_dir, *, binary=INFLUX_CLI_BINARY):
    """Argv for the official ``influx backup`` run directly in this container."""
    return [binary, "backup", staging_dir]


def build_influx_cli_restore_argv(staging_dir, *, binary=INFLUX_CLI_BINARY):
    """Argv for the official ``influx restore --full`` run directly in-container."""
    return [binary, "restore", "--full", staging_dir]


def influx_cli_env(url, token, *, environ=None):
    """Environment for the in-container influx CLI; keeps host/token out of argv."""
    env = dict(os.environ if environ is None else environ)
    env["INFLUX_HOST"] = url
    env["INFLUX_TOKEN"] = token
    return env
