# SPDX-License-Identifier: AGPL-3.0-or-later
# /var/log/journal exists on this image, so journald stores persistently and its
# defaults apply: SystemMaxUse is 10% of the filesystem. On the persistent
# partition that is hundreds of megabytes of continuously rewritten journal on
# an SD card, against a budget appliance/media_sizing.py already accounts for.
# Bounded here against that budget rather than against whatever the card turns
# out to be.
[Journal]
Storage=persistent
Compress=yes
SystemMaxUse=128M
SystemMaxFileSize=16M
MaxRetentionSec=1month
