# SPDX-License-Identifier: AGPL-3.0-or-later
"""A fake A/B appliance host: a fixture tree plus a scripted block layer.

The tree models an ``image-rota`` appliance: GPT labels rather than pinned
PARTUUIDs, ``/dev/disk/by-slot`` aliases, ``/bootfs`` carrying the selector,
``/persistent`` carrying every shared path, and a read-only root.

Every signal ``appliance/ab_layout.py`` reads comes from a file under one
temporary root or from the recording command runner, so the whole discovery and
update path is testable on a normal developer machine with no loop devices, no
root and no Raspberry Pi. What this harness deliberately does **not** model is
the firmware itself: whether a real bootloader honours ``tryboot`` is a hardware
question, answered in docs/appliance/ab-hardware-validation.md.
"""

import json
import struct
from pathlib import Path
from types import SimpleNamespace

from appliance import ab_docker_health
from appliance.commands import CommandResult, RecordingRunner

DEVICE = "/dev/mmcblk0"
BOOT_MODE_SD = 1

LAYOUT_ID = "ems-appliance-rota-v1"
IMAGE_LAYER_VERSION = "5.5.1"

SLOT_PREFIX = "/dev/disk/by-slot"

# Generated by genimage per build, never pinned by this project. They are here
# only so the fixture's block layer can report something plausible.
PARTUUIDS = {
    "bootconfig": "0000ab01-0001-4a01-8a01-000000000001",
    "boot_a": "0000ab01-0002-4a01-8a01-000000000002",
    "boot_b": "0000ab01-0003-4a01-8a01-000000000003",
    "system_a": "0000ab01-0004-4a01-8a01-000000000004",
    "system_b": "0000ab01-0005-4a01-8a01-000000000005",
    "persistent": "0000ab01-0006-4a01-8a01-000000000006",
}

PARTITIONS = (
    ("bootconfig", 1, f"{DEVICE}p1", "vfat", "bootconfig", 32 * 1024 * 1024),
    ("boot_a", 2, f"{DEVICE}p2", "vfat", "boot_a", 128 * 1024 * 1024),
    ("boot_b", 3, f"{DEVICE}p3", "vfat", "boot_b", 128 * 1024 * 1024),
    ("system_a", 4, f"{DEVICE}p4", "ext4", "system_a", 8 * 1024 * 1024 * 1024),
    ("system_b", 5, f"{DEVICE}p5", "ext4", "system_b", 8 * 1024 * 1024 * 1024),
    ("persistent", 6, f"{DEVICE}p6", "ext4", "persistent", 4 * 1024 * 1024 * 1024),
)

SELECTOR_MOUNT = "/bootfs"
PERSIST_MOUNT = "/persistent"
SHARED_ROOT = "/persistent/shared"
BOOT_MOUNT = "/boot/firmware"
MACHINE_ID_SOURCE = "/persistent/common/etc/machine-id"
MACHINE_ID = "0123456789abcdef0123456789abcdef"

SLOT_BOOT_PARTITION = {"A": 2, "B": 3}
SLOT_LABELS = {
    "A": {"boot": "boot_a", "root": "system_a"},
    "B": {"boot": "boot_b", "root": "system_b"},
}

DEFAULT_OS_BUILD = {
    "release_version": "1.4.0",
    "build_id": "20260801-1",
    "layout_id": LAYOUT_ID,
    "artifact_digest": "sha256:" + "a" * 64,
    "rootfs_digest": "sha256:" + "b" * 64,
    "persistent_schema_version": 2,
    "slot_schema_version": 2,
}


def layout_manifest():
    return {
        "schema_version": 2,
        "layout_id": LAYOUT_ID,
        "slot_schema_version": 2,
        "persistent_schema_version": 2,
        "image_layer": "image-rota",
        "image_layer_version": IMAGE_LAYER_VERSION,
        "slot_device_prefix": SLOT_PREFIX,
        "bootconfig": {"label": "bootconfig", "fstype": "vfat"},
        "persist": {"label": "persistent", "fstype": "ext4"},
        "selector_mountpoint": SELECTOR_MOUNT,
        "persist_mountpoint": PERSIST_MOUNT,
        "boot_mountpoint": BOOT_MOUNT,
        "shared_root": SHARED_ROOT,
        "machine_id_source": MACHINE_ID_SOURCE,
        "slots": {
            name: {
                "boot": {"label": labels["boot"], "fstype": "vfat"},
                "root": {"label": labels["root"], "fstype": "ext4"},
            }
            for name, labels in SLOT_LABELS.items()
        },
    }


def device_of(key):
    for name, _number, path, _fstype, _label, _size in PARTITIONS:
        if name == key:
            return path
    raise KeyError(key)


def lsblk_payload(*, omit=(), device=DEVICE, sizes=None, extra=()):
    sizes = dict(sizes or {})
    children = []
    for key, number, path, fstype, label, size in PARTITIONS:
        if key in omit:
            continue
        children.append(
            {
                "path": path,
                "type": "part",
                "size": sizes.get(key, size),
                "partuuid": PARTUUIDS[key],
                "partlabel": label,
                "fstype": fstype,
                "mountpoint": None,
                "pkname": device,
                "partn": number,
            }
        )
    blockdevices = [
        {"path": device, "type": "disk", "size": 32 * 1024**3, "children": children}
    ]
    blockdevices.extend(extra)
    return {"blockdevices": blockdevices}


def second_medium(device="/dev/sda"):
    """A second appliance medium: the same labels on a different disk."""

    children = []
    for key, number, _path, fstype, label, size in PARTITIONS:
        children.append(
            {
                "path": f"{device}{number}",
                "type": "part",
                "size": size,
                # A different build, so different identities under the same labels.
                "partuuid": PARTUUIDS[key].replace("0000ab01", "0000cd02"),
                "partlabel": label,
                "fstype": fstype,
                "mountpoint": None,
                "pkname": device,
                "partn": number,
            }
        )
    return {"path": device, "type": "disk", "size": 32 * 1024**3, "children": children}


class ApplianceAbHost:
    """One temporary root that looks like a booted image-rota appliance."""

    def __init__(self, tmp_path, *, slot="A", tryboot=False):
        self.root = Path(tmp_path) / "host"
        self.root.mkdir(parents=True, exist_ok=True)
        self.slot = slot
        self._tryboot = tryboot
        self._mounts = {}
        self._lsblk = lsblk_payload()
        self.write_layout_manifest(layout_manifest())
        self.write_selector(default=SLOT_BOOT_PARTITION["A"], trial=SLOT_BOOT_PARTITION["B"])
        self.write_os_build(DEFAULT_OS_BUILD)
        self.write_board("raspberrypi,4-model-b")
        self.boot_slot(slot, tryboot=tryboot)
        self.seed_persistent_tree()
        self.seed_host_identity()
        self.mount_defaults()

    # --- fixture files ---------------------------------------------------

    def _write(self, relative, text):
        path = self.root / str(relative).lstrip("/")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def _symlink(self, relative, target):
        path = self.root / str(relative).lstrip("/")
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink() or path.exists():
            path.unlink()
        path.symlink_to(target)
        return path

    def write_layout_manifest(self, payload):
        return self._write(
            "etc/ems-appliance-manager/ab-layout.json", json.dumps(payload, indent=2) + "\n"
        )

    def remove_layout_manifest(self):
        (self.root / "etc/ems-appliance-manager/ab-layout.json").unlink()
        return self

    def write_os_build(self, payload):
        return self._write("etc/ems-appliance-os-build", json.dumps(payload) + "\n")

    def write_selector(self, *, default, trial, text=None):
        body = text
        if body is None:
            body = (
                "# ems-appliance boot selector. Generated; do not edit.\n"
                "[all]\ntryboot_a_b=1\n"
                f"boot_partition={default}\n"
                "\n[tryboot]\n"
                f"boot_partition={trial}\n"
            )
        return self._write(f"{SELECTOR_MOUNT.lstrip('/')}/autoboot.txt", body)

    def selector_path(self):
        return self.root / SELECTOR_MOUNT.lstrip("/") / "autoboot.txt"

    def write_board(self, compatible):
        path = self.root / "proc/device-tree/compatible"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(compatible.encode("utf-8") + b"\x00")
        return path

    def slot_boot_partition(self, slot):
        return SLOT_BOOT_PARTITION[slot]

    def seed_persistent_tree(self):
        """The subtree upstream's generator binds every shared path from."""

        from appliance import ab_persistence

        for shared in ab_persistence.SHARED_PATHS:
            (self.root / f"persistent/shared{shared.target}".lstrip("/")).mkdir(
                parents=True, exist_ok=True
            )
        for directory in (
            "opt/ems-solarflow/config",
            "opt/ems-solarflow/data",
            "opt/ems-solarflow/backups",
            "var/lib/ems-appliance-manager/ssh",
            "var/lib/ems-appliance-os-update",
            "etc/NetworkManager/system-connections",
            "persistent/common/etc",
            "persistent/home",
        ):
            (self.root / directory).mkdir(parents=True, exist_ok=True)
        self._write(MACHINE_ID_SOURCE, MACHINE_ID + "\n")
        self._write("etc/machine-id", MACHINE_ID + "\n")
        return self

    def seed_host_identity(self):
        """The persistent SSH identity an OS update is only planned against.

        The private keys are fixture bytes, but the pairing is not faked: the
        runner answers ``ssh-keygen -y`` from this table, so a test that breaks
        the pairing fails the same verification a real appliance runs.
        """

        import base64
        import os as _os

        from appliance import host_identity

        directory = self.root / str(host_identity.KEY_DIRECTORY).lstrip("/")
        directory.mkdir(parents=True, exist_ok=True)
        _os.chmod(directory, host_identity.DIRECTORY_MODE)
        self.host_keys = {}
        for key_type in host_identity.HOST_KEY_TYPES:
            private = directory / host_identity.private_key_name(key_type)
            public = directory / host_identity.public_key_name(key_type)
            blob = base64.b64encode(f"{key_type}-fixture-host-key".encode("utf-8")).decode()
            material = f"ssh-{key_type} {blob}"
            private.write_text(
                f"-----BEGIN OPENSSH PRIVATE KEY-----\n{blob}\n"
                "-----END OPENSSH PRIVATE KEY-----\n",
                encoding="utf-8",
            )
            _os.chmod(private, host_identity.PRIVATE_MODE)
            public.write_text(f"{material} ems-appliance\n", encoding="utf-8")
            _os.chmod(public, host_identity.PUBLIC_MODE)
            self.host_keys[str(private)] = material
        self._write(
            host_identity.DROP_IN,
            "".join(
                f"HostKey {host_identity.KEY_DIRECTORY}/"
                f"{host_identity.private_key_name(key_type)}\n"
                for key_type in host_identity.HOST_KEY_TYPES
            ),
        )
        return self

    @property
    def ab_state_dir(self):
        return self.root / "var/lib/ems-appliance-os-update"

    def boot_slot(self, slot, *, tryboot=None):
        """Say which partition the firmware booted, and how."""

        self.slot = slot
        if tryboot is not None:
            self._tryboot = tryboot
        self._write_cell("proc/device-tree/chosen/bootloader/partition", SLOT_BOOT_PARTITION[slot])
        self._write_cell("proc/device-tree/chosen/bootloader/boot-mode", BOOT_MODE_SD)
        self._write_cell("proc/device-tree/chosen/bootloader/tryboot", 1 if self._tryboot else 0)
        self._write(
            "proc/cmdline",
            f"console=serial0,115200 root={SLOT_PREFIX}/active/system rootwait ro\n",
        )
        self.write_slot_links(slot)
        return self

    def write_slot_links(self, slot):
        """Upstream's slot mapper publishes these; discovery cross-checks them."""

        other = "B" if slot == "A" else "A"
        prefix = SLOT_PREFIX.lstrip("/")
        self._symlink(f"{prefix}/active/boot", device_of(SLOT_LABELS[slot]["boot"]))
        self._symlink(f"{prefix}/active/system", device_of(SLOT_LABELS[slot]["root"]))
        self._symlink(f"{prefix}/other/boot", device_of(SLOT_LABELS[other]["boot"]))
        self._symlink(f"{prefix}/other/system", device_of(SLOT_LABELS[other]["root"]))
        self._symlink(f"{prefix}/persistent", device_of("persistent"))
        return self

    def boot_partition_directly(self, partition):
        self._write_cell("proc/device-tree/chosen/bootloader/partition", partition)
        return self

    def set_boot_mode(self, mode):
        self._write_cell("proc/device-tree/chosen/bootloader/boot-mode", mode)
        return self

    def _write_cell(self, relative, value):
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(struct.pack(">I", int(value)))
        return path

    # --- mount table -----------------------------------------------------

    def mount(self, target, source, *, options=("rw", "relatime"), fstype="ext4", subtree="/"):
        self._mounts[target] = {
            "source": source,
            "options": tuple(options),
            "fstype": fstype,
            "root": subtree,
        }
        return self._render_mountinfo()

    def unmount(self, target):
        self._mounts.pop(target, None)
        return self._render_mountinfo()

    def mount_defaults(self):
        from appliance import ab_persistence

        persistent = f"{SLOT_PREFIX}/persistent"
        self._mounts = {}
        # image-rota mounts the root filesystem read-only through the slot alias.
        self.mount("/", f"{SLOT_PREFIX}/active/system", options=("ro", "relatime"))
        self.mount(
            BOOT_MOUNT, f"{SLOT_PREFIX}/active/boot", options=("ro", "noatime"), fstype="vfat"
        )
        self.mount(SELECTOR_MOUNT, device_of("bootconfig"), options=("ro", "noatime"), fstype="vfat")
        self.mount(PERSIST_MOUNT, persistent, options=("rw", "noatime"))
        for shared in ab_persistence.SHARED_PATHS:
            self.mount(
                shared.target,
                persistent,
                options=("rw", "noatime"),
                subtree=ab_persistence.shared_subtree(shared),
            )
        return self._render_mountinfo()

    def _render_mountinfo(self):
        lines = []
        for index, (target, record) in enumerate(sorted(self._mounts.items()), start=20):
            lines.append(
                " ".join(
                    [
                        str(index),
                        "1",
                        "179:1",
                        record["root"],
                        target,
                        ",".join(record["options"]),
                        "-",
                        record["fstype"],
                        record["source"],
                        "rw",
                    ]
                )
            )
        self._write("proc/1/mountinfo", "\n".join(lines) + "\n")
        return self

    def apply_mounts(self):
        return self._render_mountinfo()

    def mounts(self):
        return {
            target: {
                "options": frozenset(record["options"]),
                "fstype": record["fstype"],
                "source": record["source"],
                "root": record["root"],
            }
            for target, record in self._mounts.items()
        }

    # --- block layer -----------------------------------------------------

    def set_block_devices(self, payload):
        self._lsblk = payload
        return self

    def attach_second_medium(self, device="/dev/sda"):
        """Another appliance's card in a reader: same labels, other disk."""

        self._lsblk = lsblk_payload(extra=(second_medium(device),))
        return self

    def runner(self, *, lsblk_ok=True, available=True):
        payload = json.dumps(self._lsblk)
        host_keys = dict(getattr(self, "host_keys", {}))

        class _Runner(RecordingRunner):
            def available(self, tool):
                if tool == "lsblk" and not available:
                    return False
                return super().available(tool)

            def run(self, tool, args=(), **kwargs):
                args = tuple(args)
                if tool == "ssh-keygen" and args[:1] == ("-y",) and len(args) >= 3:
                    material = host_keys.get(args[2])
                    if material is None:
                        return CommandResult(tool, args, 1, "", "no such private key")
                    return CommandResult(tool, args, 0, material + "\n", "")
                return super().run(tool, args, **kwargs)

        replies = {
            "lsblk": CommandResult(
                "lsblk", (), 0 if lsblk_ok else 1, payload if lsblk_ok else "", ""
            )
        }
        return _Runner(replies, default="")

    def probe(self, **kwargs):
        from appliance.ab_layout import LayoutProbe

        runner = kwargs.pop("runner", None) or self.runner(**kwargs)
        return LayoutProbe(root=self.root, runner=runner)

    def discover(self, **kwargs):
        from appliance.ab_layout import discover

        self.apply_mounts()
        return discover(self.probe(**kwargs))


class FakeSystemd:
    def __init__(self, *, active=("ems-appliance-agent.service", "ems-appliance-web.service")):
        self.active = set(active)
        self.reboots = 0
        self.reboot_ok = True

    def is_active(self, unit):
        return unit in self.active

    def reboot(self):
        self.reboots += 1
        return SimpleNamespace(ok=self.reboot_ok)


class FakeDocker:
    """The same protocol production implements, and no other method names."""

    def __init__(self, *, daemon=True, admin=True, ems=True):
        self.daemon = daemon
        self.admin = admin
        self.ems = ems

    def daemon_usable(self):
        if self.daemon:
            return ab_docker_health.passed("the fake Docker daemon answers")
        return ab_docker_health.failed("docker_daemon_unreachable", "the daemon is down")

    def admin_runtime(self, expected_digest):
        if self.admin:
            return ab_docker_health.passed("the Admin container answers")
        return ab_docker_health.failed("admin_container_missing", "no Admin container")

    def ems_runtime(self, expected_digest, *, expected_running=True):
        if self.ems or not expected_running:
            return ab_docker_health.passed("the EMS deployment is as recorded")
        return ab_docker_health.failed("ems_container_not_running", "EMS is not running")


def build_ab_service(
    tmp_path,
    host,
    releases,
    *,
    backend=None,
    time_fn=None,
    appliance_version="0.9.0",
    minimum_staging_bytes=0,
    inspector=None,
    **overrides,
):
    """The whole A/B update service, wired against one fake appliance host."""

    from appliance import ab_blocks
    from appliance.ab_state import AbStateStore
    from appliance.operations import OperationStore
    from appliance.os_update import OsUpdateService

    sizes = {}
    for _key, _number, path, _fstype, _label, size in PARTITIONS:
        sizes[path] = size
    backend = backend or ab_blocks.FakeBlockBackend(sizes=sizes)
    state = AbStateStore(host.ab_state_dir, time_fn=time_fn)
    state.ensure()
    runner = host.runner()
    service = OsUpdateService(
        paths=SimpleNamespace(state_dir=Path(tmp_path) / "state"),
        config=SimpleNamespace(),
        operations=OperationStore(Path(tmp_path) / "operations"),
        catalogue=releases.catalogue(),
        state=state,
        probe=host.probe(runner=runner),
        backend=backend,
        runner=runner,
        time_fn=time_fn,
        appliance_version=appliance_version,
        minimum_staging_bytes=minimum_staging_bytes,
        inspector=inspector if inspector is not None else AcceptingInspector(),
        # The fixture selector is a plain file, not a FAT mount, so there is
        # nothing to remount. The remount itself is covered in the selector tests.
        remount_selector=False,
        **overrides,
    )
    return service


class AcceptingInspector:
    """An inactive-slot inspector that finds nothing wrong, and says so."""

    def __init__(self, *, report=None, leaked=False):
        self.calls = []
        self.leak_checks = 0
        self._report = report
        self._leaked = leaked

    def assert_no_leak(self):
        from appliance.ab_inspect import InspectionError

        self.leak_checks += 1
        if self._leaked:
            raise InspectionError(
                "inspection_mount_leaked",
                "a previous inactive-slot inspection left a mount behind",
            )

    def inspect(self, authority, release, **kwargs):
        from appliance.ab_inspect import InspectionReport

        self.calls.append({"authority": authority, "release": release, **kwargs})
        if self._report is not None:
            return self._report
        return InspectionReport(target_slot=authority.target_slot, findings=(), cleaned=True)


def build_health_service(host, state, *, runner=None, systemd=None, docker=None, **kwargs):
    from appliance.ab_health import TrialHealthService

    return TrialHealthService(
        probe=host.probe(),
        state=state,
        selector_path=host.selector_path(),
        runner=runner,
        systemd=systemd if systemd is not None else FakeSystemd(),
        docker=docker if docker is not None else FakeDocker(),
        install_check=kwargs.pop("install_check", lambda: True),
        agent_socket=kwargs.pop("agent_socket", lambda: True),
        remount_selector=kwargs.pop("remount_selector", False),
        **kwargs,
    )


class BootFlowSimulator:
    """Drive a whole A/B update across simulated reboots, deterministically.

    The firmware is modelled, not emulated: a reboot reads the selector the
    appliance wrote and boots the partition it names, consuming the one-shot
    tryboot flag exactly once. That is enough to prove the state machine, and
    deliberately not enough to prove a real bootloader — see
    docs/appliance/ab-hardware-validation.md.
    """

    def __init__(self, tmp_path, releases, *, slot="A"):
        from appliance.ab_health import classify_fallback

        self.tmp_path = tmp_path
        self.releases = releases
        self.host = ApplianceAbHost(tmp_path, slot=slot)
        self.service = build_ab_service(tmp_path, self.host, releases)
        self.state = self.service.state
        self.systemd = FakeSystemd()
        self.boots = []
        self.fallbacks = []
        self._classify = classify_fallback

    # --- the appliance ---------------------------------------------------

    def selector(self):
        from appliance.ab_boot import parse_selector

        return parse_selector(self.host.selector_path().read_text(encoding="utf-8"))

    def slot_of(self, partition):
        for slot, number in SLOT_BOOT_PARTITION.items():
            if number == partition:
                return slot
        raise AssertionError(f"partition {partition} is not a slot boot partition")

    def health(self, **kwargs):
        return build_health_service(self.host, self.state, **kwargs)

    # --- reboots ---------------------------------------------------------

    def reboot(self, *, trial=False, build_id=None):
        """One boot. ``trial`` consumes the firmware's one-shot tryboot flag."""

        selector = self.selector()
        partition = selector.tryboot_partition if trial else selector.default_partition
        slot = self.slot_of(partition)
        self.host.boot_slot(slot, tryboot=trial)
        if build_id is not None:
            self.host.write_os_build(dict(DEFAULT_OS_BUILD) | {"build_id": build_id})
        self.host.mount_defaults()
        self.service.probe = self.host.probe()
        self.boots.append({"slot": slot, "trial": trial})
        if not trial:
            record = self._classify(self.host.probe(), self.state)
            if record is not None:
                self.fallbacks.append(record)
        return slot

    # --- the update ------------------------------------------------------

    def plan_update(self, release_id):
        operation = self.service.operations.create("ab.update")
        return operation, self.service.plan_update(operation, release_id)

    def plan_rollback(self):
        operation = self.service.operations.create("ab.rollback")
        return operation, self.service.plan_rollback(operation)

    def confirm(self, operation):
        self.service.operations.await_confirmation(operation.operation_id, {"plan": True})
        record = self.service.operations.get(operation.operation_id, include_token=True)
        self.service.operations.confirm(operation.operation_id, record.confirmation_token)
        return self.service.execute(operation)
