# SPDX-License-Identifier: AGPL-3.0-or-later
"""Real workflow + exact-preview authority for Guided Setup mutation tests.

Setup write/apply refuse a request that does not present the active
``setup_workflow_id`` and the exact ``config_preview_id`` the server issued for
this mutation input. Tests that drive those routes directly stand in for a
browser that confirmed Fresh Setup and reviewed the preview first, so they
perform the same two backend steps rather than weakening the contract.
"""

import hashlib
import json
from pathlib import Path

from admin.install_context import detect_install_context


def live_config_revision(base_dir=None, config_path=None):
    """``config_path`` overrides resolution for a harness with its own root."""

    path = Path(config_path or detect_install_context(base_dir=base_dir).config_path)
    try:
        raw = path.read_bytes()
    except OSError:
        return {"expected_revision": None, "expect_absent": True}
    return {
        "expected_revision": hashlib.sha256(raw).hexdigest(),
        "expect_absent": False,
    }


def adopt_generated_config(service, *, draft_fingerprint="sha256:" + "0" * 64):
    """Bind a DeploymentService's current generated bytes to an active workflow.

    Stands in for the preview+write flow for service-level tests that stage
    generated bytes directly: records a preview whose payload hash matches the
    bytes on disk (baseline = the workspace's current live config state) and
    writes the ownership metadata sidecar. Re-run it after a test rewrites the
    generated bytes.
    """

    from admin.guided_setup_workflow import GuidedSetupWorkflowStore
    from admin.setup_workflow import (
        GENERATED_CONFIG_META_VERSION,
        GENERATED_CONFIG_OWNER,
    )

    store = service.setup_workflows
    if store is None:
        store = GuidedSetupWorkflowStore(service.admin_data_dir)
        service.setup_workflows = store
    record = store.ensure_active()
    workflow_id = record["workflow_id"]
    target = Path(service.config_export.target_path)
    payload = target.read_bytes()
    prepared_sha256 = hashlib.sha256(payload).hexdigest()
    live = Path(service.workspace_dir) / "config" / "config.json"
    base_config_revision = live_config_revision(config_path=live)
    record = store.record_preview(
        workflow_id,
        draft_fingerprint=draft_fingerprint,
        base_config_revision=base_config_revision,
        prepared_config_sha256=prepared_sha256,
    )
    store.bind_generated_artifacts(
        workflow_id, preview_id=record["preview"]["preview_id"]
    )
    meta = {
        "format_version": GENERATED_CONFIG_META_VERSION,
        "owner": GENERATED_CONFIG_OWNER,
        "workflow_id": workflow_id,
        "preview_id": record["preview"]["preview_id"],
        "draft_fingerprint": draft_fingerprint,
        "base_config_revision": base_config_revision,
        "prepared_config_sha256": prepared_sha256,
        "recorded_at": "2026-07-29T00:00:00Z",
    }
    (target.parent / "config.meta.json").write_text(
        json.dumps(meta, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return store


def own_active_setup_transition(srv, base, request, workflow_id):
    """Give ``workflow_id`` the transition ownership production writes pre-commit.

    Production links a Setup transition into its workflow record inside the
    System Alignment pre-commit boundary, so a workflow that reached a
    transition always names its exact ``operation_id``. A harness that
    *pre-seeds* an active Setup transition has to establish the same fact, or
    the workflow it starts is an unlinked owner — a state the ownership rules
    refuse on purpose, entry included.
    """

    _status, _headers, payload = request(f"{base}/api/admin/system-alignment/status")
    transition = (payload or {}).get("transition") or {}
    if transition.get("mode") not in {"fresh_install", "automated_setup"}:
        return None
    return srv.setup_workflows.record_transition(
        workflow_id,
        operation_id=transition.get("operation_id"),
        transition_mode=transition["mode"],
        selected_system_tag=transition.get("system_tag"),
    )


def start_setup_workflow(base, request, srv=None):
    """Confirm Fresh Setup and return the durable ``setup_workflow_id``.

    Pass ``srv`` whenever the harness pre-seeds an active Setup transition
    (``SetupReadySystemAlignment`` and friends): the started workflow then owns
    it exactly as production would, so a second entry is not refused as an
    unprovable owner.
    """

    status, _, payload = request(
        f"{base}/api/admin/start-path",
        method="POST",
        body={"choice": "setup_new", "confirm": True},
    )
    assert status == 200 and payload.get("ok") is True, payload
    workflow_id = payload.get("setup_workflow_id")
    assert workflow_id, "start-path must issue a setup_workflow_id"
    if srv is not None:
        own_active_setup_transition(srv, base, request, workflow_id)
    return workflow_id


def current_device_plan_id(base, request, state=None):
    """Plan the current devices and return the issued ``device_plan_id``.

    Setup Config Preview only issues mutation authority for a device plan this
    server issued and still considers current, so a test that drives the
    mutation routes performs the same planning step the browser does.
    """

    status, _, plan = request(
        f"{base}/api/setup/device-plan", method="POST", body={"state": state or {}}
    )
    assert status == 200, plan
    return plan["plan_id"]


def authorize_setup_mutation(base, request, body, *, workflow_id=None, srv=None):
    """Return ``body`` carrying real workflow, device-plan and preview authority.

    ``request`` is the caller's authenticated HTTP helper
    (``request(url, method=..., body=...) -> (status, headers, payload)``).
    The preview must be ready — a draft that cannot preview cannot be
    authorized, exactly like in the browser. ``srv`` is forwarded to
    :func:`start_setup_workflow` for harnesses that pre-seed a transition.
    """

    workflow_id = workflow_id or start_setup_workflow(base, request, srv)
    authorized = {
        key: value
        for key, value in dict(body or {}).items()
        if key != "config_revision"
    }
    authorized["setup_workflow_id"] = workflow_id
    authorized.setdefault("device_plan_id", current_device_plan_id(base, request))
    status, _, preview = request(
        f"{base}/api/setup/config-preview", method="POST", body=authorized
    )
    assert status == 200, preview
    preview_id = preview.get("config_preview_id")
    assert preview_id, (
        "the draft did not produce a ready preview: "
        f"{(preview.get('validation') or {}).get('errors')}"
    )
    authorized["config_preview_id"] = preview_id
    return authorized
